name: dcase2020_workshop
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - audioread=2.1.8
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.2.2
  - fontconfig=2.13.0
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - gnutls=3.6.5
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - intel-openmp=2020.1
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm8=8.0.1
  - libogg=1.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.9.0
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1g
  - pandas=1.0.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pymongo=3.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - resampy=0.2.2
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=47.3.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.2
  - tbb=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tornado=6.0.4
  - tqdm=4.46.1
  - traitlets=4.3.3
  - typing=3.7.4.1
  - wcwidth=0.2.4
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - colorama==0.4.3
    - docopt==0.6.2
    - future==0.18.2
    - gitdb==4.0.2
    - gitpython==3.1.0
    - google-auth==1.11.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - joblib==0.14.1
    - jsonpickle==1.3
    - markdown==3.2.1
    - munch==2.5.0
    - oauthlib==3.1.0
    - packaging==20.3
    - protobuf==3.11.3
    - py-cpuinfo==5.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==0.8.1
    - pyyaml==5.3.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sacred==0.8.1
    - scikit-learn==0.22.2.post1
    - smmap==3.0.1
    - soundfile==0.10.3.post1
    - squarify==0.4.3
    - tensorboard==2.1.1
    - urllib3==1.25.8
    - werkzeug==1.0.0
    - wrapt==1.12.1

